# Opções globais (fora dos blocos)
splash = false
ipc = true

# Bloco para o monitor do notebook
wallpaper {
    monitor = eDP-1
    path = ~/.config/background/girl-reading-book.png
    fit_mode = cover
}

# Bloco de fallback (para qualquer outro monitor, como o seu HDMI)
wallpaper {
    monitor = 
    path = ~/.config/background/girl-reading-book.png
    fit_mode = cover
}